[2022-03-27 08:21:05,262] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator.get_sql manual__2022-03-27T13:20:56.346726+00:00 [queued]>
[2022-03-27 08:21:05,268] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator.get_sql manual__2022-03-27T13:20:56.346726+00:00 [queued]>
[2022-03-27 08:21:05,268] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 08:21:05,268] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-27 08:21:05,268] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 08:21:06,958] {taskinstance.py:1264} INFO - Executing <Task(_PythonDecoratedOperator): get_sql> on 2022-03-27 13:20:56.346726+00:00
[2022-03-27 08:21:06,962] {standard_task_runner.py:52} INFO - Started process 2828 to run task
[2022-03-27 08:21:06,965] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'python_operator', 'get_sql', 'manual__2022-03-27T13:20:56.346726+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/etl_python_operator.py', '--cfg-path', '/tmp/tmph_45d5ei', '--error-file', '/tmp/tmpx4r856i9']
[2022-03-27 08:21:06,966] {standard_task_runner.py:77} INFO - Job 113: Subtask get_sql
[2022-03-27 08:21:07,256] {logging_mixin.py:109} INFO - Running <TaskInstance: python_operator.get_sql manual__2022-03-27T13:20:56.346726+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-03-27 08:21:07,748] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=python_operator
AIRFLOW_CTX_TASK_ID=get_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-03-27T13:20:56.346726+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-27T13:20:56.346726+00:00
[2022-03-27 08:21:07,753] {base.py:70} INFO - Using connection to: id: airflow-universities. Host: training-main.cghe7e6sfljt.us-east-1.rds.amazonaws.com, Port: 5432, Schema: training, Login: alkymer, Password: ***, extra: {}
[2022-03-27 08:21:08,486] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/etl_python_operator.py", line 26, in get_data_uba
    cur.execute(query)
psycopg2.errors.UndefinedColumn: column "careers" does not exist
LINE 1: select universidades, careers, inscription_dates, names, loc...
                              ^
HINT:  Perhaps you meant to reference the column "uba_kenedy.carreras".

[2022-03-27 08:21:08,494] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=python_operator, task_id=get_sql, execution_date=20220327T132056, start_date=20220327T132105, end_date=20220327T132108
[2022-03-27 08:21:10,605] {standard_task_runner.py:89} ERROR - Failed to execute job 113 for task get_sql
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/etl_python_operator.py", line 26, in get_data_uba
    cur.execute(query)
psycopg2.errors.UndefinedColumn: column "careers" does not exist
LINE 1: select universidades, careers, inscription_dates, names, loc...
                              ^
HINT:  Perhaps you meant to reference the column "uba_kenedy.carreras".

[2022-03-27 08:21:10,644] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-27 08:21:11,246] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
