[2022-03-22 06:14:41,855] {processor.py:163} INFO - Started process (PID=1585) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:14:41,856] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:14:41,856] {logging_mixin.py:109} INFO - [2022-03-22 06:14:41,856] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:14:41,888] {logging_mixin.py:109} INFO - [2022-03-22 06:14:41,857] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:14:41,897] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:14:43,368] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.516 seconds
[2022-03-22 06:15:30,334] {processor.py:163} INFO - Started process (PID=1606) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:15:31,163] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:15:31,163] {logging_mixin.py:109} INFO - [2022-03-22 06:15:31,163] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:15:31,165] {logging_mixin.py:109} INFO - [2022-03-22 06:15:31,165] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:15:31,172] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:15:31,423] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.091 seconds
[2022-03-22 06:16:12,990] {processor.py:163} INFO - Started process (PID=1629) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:16:12,991] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:16:12,992] {logging_mixin.py:109} INFO - [2022-03-22 06:16:12,992] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:16:12,993] {logging_mixin.py:109} INFO - [2022-03-22 06:16:12,993] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:16:13,005] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:16:13,823] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.837 seconds
[2022-03-22 06:16:53,323] {processor.py:163} INFO - Started process (PID=1648) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:16:54,217] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:16:54,218] {logging_mixin.py:109} INFO - [2022-03-22 06:16:54,218] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:16:54,220] {logging_mixin.py:109} INFO - [2022-03-22 06:16:54,219] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:16:54,235] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:16:54,370] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.049 seconds
[2022-03-22 06:17:34,075] {processor.py:163} INFO - Started process (PID=1667) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:17:34,088] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:17:34,089] {logging_mixin.py:109} INFO - [2022-03-22 06:17:34,088] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:17:34,090] {logging_mixin.py:109} INFO - [2022-03-22 06:17:34,090] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:17:34,098] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:17:35,315] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.243 seconds
[2022-03-22 06:18:17,778] {processor.py:163} INFO - Started process (PID=1688) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:18:17,916] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:18:17,916] {logging_mixin.py:109} INFO - [2022-03-22 06:18:17,916] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:18:17,919] {logging_mixin.py:109} INFO - [2022-03-22 06:18:17,918] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:18:17,929] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:18:18,890] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.115 seconds
[2022-03-22 06:19:03,641] {processor.py:163} INFO - Started process (PID=1708) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:19:04,736] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:19:04,737] {logging_mixin.py:109} INFO - [2022-03-22 06:19:04,737] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:19:04,738] {logging_mixin.py:109} INFO - [2022-03-22 06:19:04,738] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:19:04,745] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:19:05,008] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.369 seconds
[2022-03-22 06:19:45,994] {processor.py:163} INFO - Started process (PID=1729) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:19:46,603] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:19:46,604] {logging_mixin.py:109} INFO - [2022-03-22 06:19:46,604] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:19:46,605] {logging_mixin.py:109} INFO - [2022-03-22 06:19:46,605] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:19:46,613] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:19:46,811] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.819 seconds
[2022-03-22 06:20:30,220] {processor.py:163} INFO - Started process (PID=1749) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:20:30,233] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:20:30,234] {logging_mixin.py:109} INFO - [2022-03-22 06:20:30,234] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:20:30,235] {logging_mixin.py:109} INFO - [2022-03-22 06:20:30,235] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:20:30,243] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:20:31,389] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.172 seconds
[2022-03-22 06:21:14,093] {processor.py:163} INFO - Started process (PID=1770) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:21:14,270] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:21:14,271] {logging_mixin.py:109} INFO - [2022-03-22 06:21:14,271] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:21:14,275] {logging_mixin.py:109} INFO - [2022-03-22 06:21:14,273] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:21:14,288] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:21:15,040] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.949 seconds
[2022-03-22 06:21:58,579] {processor.py:163} INFO - Started process (PID=1790) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:21:59,416] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:21:59,417] {logging_mixin.py:109} INFO - [2022-03-22 06:21:59,417] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:21:59,418] {logging_mixin.py:109} INFO - [2022-03-22 06:21:59,418] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:21:59,426] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:22:00,642] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 2.065 seconds
[2022-03-22 06:22:41,985] {processor.py:163} INFO - Started process (PID=1811) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:22:42,071] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:22:42,071] {logging_mixin.py:109} INFO - [2022-03-22 06:22:42,071] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:22:42,073] {logging_mixin.py:109} INFO - [2022-03-22 06:22:42,073] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:22:42,081] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:22:43,257] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.276 seconds
[2022-03-22 06:23:17,799] {processor.py:163} INFO - Started process (PID=1829) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:23:17,802] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:23:17,802] {logging_mixin.py:109} INFO - [2022-03-22 06:23:17,802] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:23:17,804] {logging_mixin.py:109} INFO - [2022-03-22 06:23:17,803] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:23:17,812] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:23:18,519] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.722 seconds
[2022-03-22 06:23:55,677] {processor.py:163} INFO - Started process (PID=1848) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:23:56,262] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:23:56,263] {logging_mixin.py:109} INFO - [2022-03-22 06:23:56,263] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:23:56,265] {logging_mixin.py:109} INFO - [2022-03-22 06:23:56,264] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:23:56,273] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:23:56,562] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.887 seconds
[2022-03-22 06:24:36,912] {processor.py:163} INFO - Started process (PID=1867) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:24:36,916] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:24:36,916] {logging_mixin.py:109} INFO - [2022-03-22 06:24:36,916] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:24:36,919] {logging_mixin.py:109} INFO - [2022-03-22 06:24:36,918] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:24:36,929] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:24:37,874] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.966 seconds
[2022-03-22 06:25:23,528] {processor.py:163} INFO - Started process (PID=1887) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:25:23,543] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:25:23,544] {logging_mixin.py:109} INFO - [2022-03-22 06:25:23,544] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:25:23,546] {logging_mixin.py:109} INFO - [2022-03-22 06:25:23,545] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:25:23,553] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:25:23,933] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.408 seconds
[2022-03-22 06:26:13,854] {processor.py:163} INFO - Started process (PID=1909) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:26:13,873] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:26:13,873] {logging_mixin.py:109} INFO - [2022-03-22 06:26:13,873] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:26:13,875] {logging_mixin.py:109} INFO - [2022-03-22 06:26:13,874] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:26:13,884] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:26:14,037] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.185 seconds
[2022-03-22 06:27:10,902] {processor.py:163} INFO - Started process (PID=1933) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:27:10,921] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:27:10,921] {logging_mixin.py:109} INFO - [2022-03-22 06:27:10,921] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:27:10,923] {logging_mixin.py:109} INFO - [2022-03-22 06:27:10,922] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:27:10,930] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:27:12,538] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.638 seconds
[2022-03-22 06:27:57,234] {processor.py:163} INFO - Started process (PID=1955) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:27:57,703] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:27:57,703] {logging_mixin.py:109} INFO - [2022-03-22 06:27:57,703] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:27:57,705] {logging_mixin.py:109} INFO - [2022-03-22 06:27:57,704] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:27:57,714] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:27:57,905] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.675 seconds
[2022-03-22 06:28:35,208] {processor.py:163} INFO - Started process (PID=1975) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:28:35,211] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:28:35,211] {logging_mixin.py:109} INFO - [2022-03-22 06:28:35,211] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:28:35,213] {logging_mixin.py:109} INFO - [2022-03-22 06:28:35,212] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:28:35,220] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:28:36,094] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.888 seconds
[2022-03-22 06:29:15,983] {processor.py:163} INFO - Started process (PID=1994) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:29:16,511] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:29:16,512] {logging_mixin.py:109} INFO - [2022-03-22 06:29:16,512] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:29:16,514] {logging_mixin.py:109} INFO - [2022-03-22 06:29:16,513] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:29:16,521] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:29:16,678] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.698 seconds
[2022-03-22 06:29:54,204] {processor.py:163} INFO - Started process (PID=2013) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:29:54,207] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:29:54,208] {logging_mixin.py:109} INFO - [2022-03-22 06:29:54,207] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:29:54,209] {logging_mixin.py:109} INFO - [2022-03-22 06:29:54,209] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:29:54,218] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:29:55,064] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.863 seconds
[2022-03-22 06:30:37,750] {processor.py:163} INFO - Started process (PID=2033) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:30:37,863] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:30:37,864] {logging_mixin.py:109} INFO - [2022-03-22 06:30:37,864] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:30:37,866] {logging_mixin.py:109} INFO - [2022-03-22 06:30:37,866] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:30:37,877] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:30:39,808] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 2.061 seconds
[2022-03-22 06:31:25,473] {processor.py:163} INFO - Started process (PID=2053) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:31:25,488] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:31:25,489] {logging_mixin.py:109} INFO - [2022-03-22 06:31:25,488] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:31:25,491] {logging_mixin.py:109} INFO - [2022-03-22 06:31:25,490] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:31:25,499] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:31:26,506] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.036 seconds
[2022-03-22 06:32:07,437] {processor.py:163} INFO - Started process (PID=2074) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:32:07,440] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:32:07,441] {logging_mixin.py:109} INFO - [2022-03-22 06:32:07,441] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:32:07,443] {logging_mixin.py:109} INFO - [2022-03-22 06:32:07,442] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:32:07,450] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:32:07,586] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.151 seconds
[2022-03-22 06:32:56,256] {processor.py:163} INFO - Started process (PID=2094) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:32:56,661] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:32:56,662] {logging_mixin.py:109} INFO - [2022-03-22 06:32:56,662] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:32:56,664] {logging_mixin.py:109} INFO - [2022-03-22 06:32:56,663] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:32:56,676] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:32:57,546] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.292 seconds
[2022-03-22 06:33:43,479] {processor.py:163} INFO - Started process (PID=2115) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:33:43,695] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:33:43,696] {logging_mixin.py:109} INFO - [2022-03-22 06:33:43,696] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:33:43,698] {logging_mixin.py:109} INFO - [2022-03-22 06:33:43,698] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:33:43,706] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:33:44,339] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.862 seconds
[2022-03-22 06:34:33,695] {processor.py:163} INFO - Started process (PID=2136) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:34:34,452] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:34:34,453] {logging_mixin.py:109} INFO - [2022-03-22 06:34:34,453] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:34:34,455] {logging_mixin.py:109} INFO - [2022-03-22 06:34:34,454] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:34:34,464] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:34:35,553] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.863 seconds
[2022-03-22 06:35:16,886] {processor.py:163} INFO - Started process (PID=2157) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:35:16,889] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:35:16,890] {logging_mixin.py:109} INFO - [2022-03-22 06:35:16,890] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:35:16,892] {logging_mixin.py:109} INFO - [2022-03-22 06:35:16,891] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:35:16,903] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:35:17,565] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.681 seconds
[2022-03-22 06:35:55,330] {processor.py:163} INFO - Started process (PID=2176) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:35:55,364] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:35:55,364] {logging_mixin.py:109} INFO - [2022-03-22 06:35:55,364] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:35:55,366] {logging_mixin.py:109} INFO - [2022-03-22 06:35:55,365] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:35:55,373] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:35:56,323] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.996 seconds
[2022-03-22 06:36:36,049] {processor.py:163} INFO - Started process (PID=2195) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:36:36,067] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:36:36,067] {logging_mixin.py:109} INFO - [2022-03-22 06:36:36,067] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:36:36,070] {logging_mixin.py:109} INFO - [2022-03-22 06:36:36,069] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:36:36,080] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:36:37,729] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.683 seconds
[2022-03-22 06:37:16,781] {processor.py:163} INFO - Started process (PID=2215) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:37:17,551] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:37:17,552] {logging_mixin.py:109} INFO - [2022-03-22 06:37:17,552] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:37:17,556] {logging_mixin.py:109} INFO - [2022-03-22 06:37:17,554] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:37:17,569] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:37:17,737] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.958 seconds
[2022-03-22 06:37:55,719] {processor.py:163} INFO - Started process (PID=2234) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:37:55,722] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:37:55,723] {logging_mixin.py:109} INFO - [2022-03-22 06:37:55,723] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:37:55,725] {logging_mixin.py:109} INFO - [2022-03-22 06:37:55,724] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:37:55,732] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:37:57,122] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.405 seconds
[2022-03-22 06:38:39,075] {processor.py:163} INFO - Started process (PID=2254) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:38:39,297] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:38:39,297] {logging_mixin.py:109} INFO - [2022-03-22 06:38:39,297] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:38:39,299] {logging_mixin.py:109} INFO - [2022-03-22 06:38:39,298] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:38:39,306] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:38:40,233] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.161 seconds
[2022-03-22 06:39:25,353] {processor.py:163} INFO - Started process (PID=2275) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:39:25,356] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:39:25,357] {logging_mixin.py:109} INFO - [2022-03-22 06:39:25,356] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:39:25,358] {logging_mixin.py:109} INFO - [2022-03-22 06:39:25,358] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:39:25,365] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:39:26,883] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.531 seconds
[2022-03-22 06:40:08,354] {processor.py:163} INFO - Started process (PID=2295) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:40:08,361] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:40:08,362] {logging_mixin.py:109} INFO - [2022-03-22 06:40:08,362] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:40:08,363] {logging_mixin.py:109} INFO - [2022-03-22 06:40:08,363] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:40:08,371] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:40:09,352] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.001 seconds
[2022-03-22 06:40:54,814] {processor.py:163} INFO - Started process (PID=2315) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:40:54,830] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:40:54,830] {logging_mixin.py:109} INFO - [2022-03-22 06:40:54,830] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:40:54,832] {logging_mixin.py:109} INFO - [2022-03-22 06:40:54,831] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:40:54,842] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:40:57,184] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 2.372 seconds
[2022-03-22 06:41:42,547] {processor.py:163} INFO - Started process (PID=2337) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:41:42,559] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:41:42,560] {logging_mixin.py:109} INFO - [2022-03-22 06:41:42,560] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:41:42,561] {logging_mixin.py:109} INFO - [2022-03-22 06:41:42,561] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:41:42,569] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:41:44,296] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.751 seconds
[2022-03-22 06:42:25,358] {processor.py:163} INFO - Started process (PID=2357) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:42:25,361] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:42:25,361] {logging_mixin.py:109} INFO - [2022-03-22 06:42:25,361] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:42:25,363] {logging_mixin.py:109} INFO - [2022-03-22 06:42:25,362] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:42:25,373] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:42:26,103] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.747 seconds
[2022-03-22 06:42:59,172] {processor.py:163} INFO - Started process (PID=2375) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:42:59,175] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:42:59,176] {logging_mixin.py:109} INFO - [2022-03-22 06:42:59,176] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:42:59,177] {logging_mixin.py:109} INFO - [2022-03-22 06:42:59,177] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:42:59,185] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:43:01,116] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.945 seconds
[2022-03-22 06:43:39,118] {processor.py:163} INFO - Started process (PID=2393) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:43:39,121] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:43:39,121] {logging_mixin.py:109} INFO - [2022-03-22 06:43:39,121] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:43:39,123] {logging_mixin.py:109} INFO - [2022-03-22 06:43:39,122] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 33
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:43:39,130] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:43:40,640] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.524 seconds
[2022-03-22 06:44:23,602] {processor.py:163} INFO - Started process (PID=2422) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:44:23,607] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:44:23,608] {logging_mixin.py:109} INFO - [2022-03-22 06:44:23,608] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:44:23,611] {logging_mixin.py:109} INFO - [2022-03-22 06:44:23,610] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 54
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:44:23,625] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:44:23,887] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.288 seconds
[2022-03-22 06:45:09,126] {processor.py:163} INFO - Started process (PID=2442) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:45:09,329] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:45:09,330] {logging_mixin.py:109} INFO - [2022-03-22 06:45:09,330] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:45:09,332] {logging_mixin.py:109} INFO - [2022-03-22 06:45:09,331] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 54
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:45:09,341] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:45:10,702] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.578 seconds
[2022-03-22 06:46:00,696] {processor.py:163} INFO - Started process (PID=2463) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:46:00,749] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:46:00,749] {logging_mixin.py:109} INFO - [2022-03-22 06:46:00,749] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:46:00,751] {logging_mixin.py:109} INFO - [2022-03-22 06:46:00,751] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 54
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:46:00,761] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:46:02,261] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.567 seconds
[2022-03-22 06:46:43,393] {processor.py:163} INFO - Started process (PID=2491) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:46:43,403] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:46:43,404] {logging_mixin.py:109} INFO - [2022-03-22 06:46:43,404] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:46:43,405] {logging_mixin.py:109} INFO - [2022-03-22 06:46:43,405] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 54
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:46:43,414] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:46:44,104] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.714 seconds
[2022-03-22 06:47:24,904] {processor.py:163} INFO - Started process (PID=2517) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:47:24,913] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-22 06:47:24,914] {logging_mixin.py:109} INFO - [2022-03-22 06:47:24,914] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:47:24,916] {logging_mixin.py:109} INFO - [2022-03-22 06:47:24,915] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 54
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2022-03-22 06:47:24,923] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-22 06:47:26,264] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.362 seconds
