[2022-04-03 21:04:15,285] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: pandas_python_operator.process_dataframe manual__2022-04-04T02:03:58.387052+00:00 [queued]>
[2022-04-03 21:04:15,297] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: pandas_python_operator.process_dataframe manual__2022-04-04T02:03:58.387052+00:00 [queued]>
[2022-04-03 21:04:15,298] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 21:04:15,298] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-03 21:04:15,298] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 21:04:15,446] {taskinstance.py:1264} INFO - Executing <Task(_PythonDecoratedOperator): process_dataframe> on 2022-04-04 02:03:58.387052+00:00
[2022-04-03 21:04:15,450] {standard_task_runner.py:52} INFO - Started process 947 to run task
[2022-04-03 21:04:15,455] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'pandas_python_operator', 'process_dataframe', 'manual__2022-04-04T02:03:58.387052+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/ET_Univ_Villa_Maria_dag.py', '--cfg-path', '/tmp/tmp_piu0u82', '--error-file', '/tmp/tmpivd57i53']
[2022-04-03 21:04:15,456] {standard_task_runner.py:77} INFO - Job 313: Subtask process_dataframe
[2022-04-03 21:04:15,772] {logging_mixin.py:109} INFO - Running <TaskInstance: pandas_python_operator.process_dataframe manual__2022-04-04T02:03:58.387052+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-04-03 21:04:16,093] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pandas_python_operator
AIRFLOW_CTX_TASK_ID=process_dataframe
AIRFLOW_CTX_EXECUTION_DATE=2022-04-04T02:03:58.387052+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-04T02:03:58.387052+00:00
[2022-04-03 21:04:16,095] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/ET_Univ_Villa_Maria_dag.py", line 91, in process_dataframe
    log.info(f'CSV created {dataframe.columns}')
AttributeError: 'XComArg' object has no attribute 'columns'
[2022-04-03 21:04:16,106] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=pandas_python_operator, task_id=process_dataframe, execution_date=20220404T020358, start_date=20220404T020415, end_date=20220404T020416
[2022-04-03 21:04:16,289] {standard_task_runner.py:89} ERROR - Failed to execute job 313 for task process_dataframe
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/ET_Univ_Villa_Maria_dag.py", line 91, in process_dataframe
    log.info(f'CSV created {dataframe.columns}')
AttributeError: 'XComArg' object has no attribute 'columns'
[2022-04-03 21:04:16,314] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-03 21:04:17,433] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
