[2022-03-27 10:17:30,969] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator.get_sql manual__2022-03-27T15:17:23.042241+00:00 [queued]>
[2022-03-27 10:17:30,977] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator.get_sql manual__2022-03-27T15:17:23.042241+00:00 [queued]>
[2022-03-27 10:17:30,977] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 10:17:30,977] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-27 10:17:30,977] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 10:17:31,130] {taskinstance.py:1264} INFO - Executing <Task(_PythonDecoratedOperator): get_sql> on 2022-03-27 15:17:23.042241+00:00
[2022-03-27 10:17:31,134] {standard_task_runner.py:52} INFO - Started process 7263 to run task
[2022-03-27 10:17:31,142] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'python_operator', 'get_sql', 'manual__2022-03-27T15:17:23.042241+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/etl_python_operator.py', '--cfg-path', '/tmp/tmp8ugz7at0', '--error-file', '/tmp/tmpcy3jxa8_']
[2022-03-27 10:17:31,143] {standard_task_runner.py:77} INFO - Job 124: Subtask get_sql
[2022-03-27 10:17:31,464] {logging_mixin.py:109} INFO - Running <TaskInstance: python_operator.get_sql manual__2022-03-27T15:17:23.042241+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-03-27 10:17:31,836] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=python_operator
AIRFLOW_CTX_TASK_ID=get_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-03-27T15:17:23.042241+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-27T15:17:23.042241+00:00
[2022-03-27 10:17:31,837] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/etl_python_operator.py", line 24, in get_data_uba
    with open('/home/lowenhard/airflow/incude/universidad_de_buenos_aires.sql', 'r') as sqlfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lowenhard/airflow/incude/universidad_de_buenos_aires.sql'
[2022-03-27 10:17:31,847] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=python_operator, task_id=get_sql, execution_date=20220327T151723, start_date=20220327T151730, end_date=20220327T151731
[2022-03-27 10:17:31,995] {standard_task_runner.py:89} ERROR - Failed to execute job 124 for task get_sql
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/etl_python_operator.py", line 24, in get_data_uba
    with open('/home/lowenhard/airflow/incude/universidad_de_buenos_aires.sql', 'r') as sqlfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lowenhard/airflow/incude/universidad_de_buenos_aires.sql'
[2022-03-27 10:17:32,006] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-27 10:17:32,495] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
