[2022-04-04 16:09:02,970] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: s3_uni_flores.upload_to_s3 manual__2022-04-04T21:08:53.892448+00:00 [queued]>
[2022-04-04 16:09:02,977] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: s3_uni_flores.upload_to_s3 manual__2022-04-04T21:08:53.892448+00:00 [queued]>
[2022-04-04 16:09:02,977] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-04 16:09:02,977] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-04 16:09:02,977] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-04 16:09:03,135] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2022-04-04 21:08:53.892448+00:00
[2022-04-04 16:09:03,138] {standard_task_runner.py:52} INFO - Started process 5746 to run task
[2022-04-04 16:09:03,141] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 's3_uni_flores', 'upload_to_s3', 'manual__2022-04-04T21:08:53.892448+00:00', '--job-id', '354', '--raw', '--subdir', 'DAGS_FOLDER/dag_s3_universidad_de_las_flores.py', '--cfg-path', '/tmp/tmp3e1c9txe', '--error-file', '/tmp/tmp8e3w_h36']
[2022-04-04 16:09:03,142] {standard_task_runner.py:77} INFO - Job 354: Subtask upload_to_s3
[2022-04-04 16:09:03,344] {logging_mixin.py:109} INFO - Running <TaskInstance: s3_uni_flores.upload_to_s3 manual__2022-04-04T21:08:53.892448+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-04-04 16:09:03,693] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=s3_uni_flores
AIRFLOW_CTX_TASK_ID=upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-04-04T21:08:53.892448+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-04T21:08:53.892448+00:00
[2022-04-04 16:09:03,698] {base_aws.py:206} INFO - Credentials retrieved from login
[2022-04-04 16:09:04,332] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/dag_s3_universidad_de_las_flores.py", line 25, in upload_to_s3
    has_key = hook.check_for_key(key, bucket_name=bucket_name)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 369, in check_for_key
    raise e
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 363, in check_for_key
    self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2022-04-04 16:09:04,784] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=s3_uni_flores, task_id=upload_to_s3, execution_date=20220404T210853, start_date=20220404T210902, end_date=20220404T210904
[2022-04-04 16:09:05,084] {standard_task_runner.py:89} ERROR - Failed to execute job 354 for task upload_to_s3
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/dag_s3_universidad_de_las_flores.py", line 25, in upload_to_s3
    has_key = hook.check_for_key(key, bucket_name=bucket_name)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 369, in check_for_key
    raise e
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 363, in check_for_key
    self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2022-04-04 16:09:05,167] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-04 16:09:05,184] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
