[2022-03-26 19:00:07,112] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: retries_cine.uni_cine scheduled__2022-03-26T23:00:00+00:00 [queued]>
[2022-03-26 19:00:07,118] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: retries_cine.uni_cine scheduled__2022-03-26T23:00:00+00:00 [queued]>
[2022-03-26 19:00:07,119] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 19:00:07,119] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-03-26 19:00:07,119] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 19:00:07,248] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): uni_cine> on 2022-03-26 23:00:00+00:00
[2022-03-26 19:00:07,252] {standard_task_runner.py:52} INFO - Started process 1623 to run task
[2022-03-26 19:00:07,257] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'retries_cine', 'uni_cine', 'scheduled__2022-03-26T23:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/etl_retries_universidad_cine.py', '--cfg-path', '/tmp/tmpe_v6c125', '--error-file', '/tmp/tmpfrg1479r']
[2022-03-26 19:00:07,258] {standard_task_runner.py:77} INFO - Job 63: Subtask uni_cine
[2022-03-26 19:00:07,470] {logging_mixin.py:109} INFO - Running <TaskInstance: retries_cine.uni_cine scheduled__2022-03-26T23:00:00+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-03-26 19:00:07,633] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1423, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2011, in render_templates
    self.task.render_template_fields(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1108, in render_template
    template = jinja_env.get_template(content)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: universidad_del_cine.sql
[2022-03-26 19:00:07,640] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=retries_cine, task_id=uni_cine, execution_date=20220326T230000, start_date=20220327T000007, end_date=20220327T000007
[2022-03-26 19:00:07,879] {standard_task_runner.py:89} ERROR - Failed to execute job 63 for task uni_cine
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1423, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2011, in render_templates
    self.task.render_template_fields(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1108, in render_template
    template = jinja_env.get_template(content)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: universidad_del_cine.sql
[2022-03-26 19:00:07,915] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-26 19:00:07,934] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
